=== matusievic/JWD_Task03_3/src/main/resources/xml/oldcards.xsd
<schema xmlns="http://www.w3.org/2001/XMLSchema"
        targetNamespace="http://www.tc.by/oldcards"
        xmlns:tns="http://www.tc.by/oldcards">

    <element name="oldcards">
        <complexType>
            <sequence>
                <element name="card" type="tns:Card" minOccurs="1" maxOccurs="unbounded"/>
            </sequence>
        </complexType>
    </element>

    <complexType name="Card">
        <sequence>
            <element name="country" type="string"/>
            <element name="year" type="tns:CardYear"/>
            <element name="authors" type="tns:Authors" minOccurs="0" maxOccurs="1"/>
            <element name="theme" type="tns:Theme"/>
            <element name="valuable" type="tns:Valuable"/>
            <element name="type" type="tns:Type"/>
        </sequence>
        <attribute name="id" type="ID" use="required"/>
        <attribute name="isSent" type="boolean" default="false"/>
    </complexType>



    <!-- Authors definition-->

    <simpleType name="Name">
        <restriction base="string">
            <pattern value="[A-Z][a-z]+"/>
        </restriction>
    </simpleType>

    <complexType name="Person">
        <sequence>
            <element name="name" type="tns:Name"/>
            <element name="surname" type="tns:Name"/>
        </sequence>
    </complexType>

    <complexType name="Author">
        <complexContent>
            <extension base="tns:Person">
                <sequence>
                    <element name="salary" type="float"/>
                </sequence>
            </extension>
        </complexContent>
    </complexType>

    <complexType name="Authors">
        <sequence>
            <element name="author" type="tns:Author" minOccurs="1" maxOccurs="unbounded"/>
        </sequence>
        <attribute name="isKnown" type="boolean" use="required"/>
    </complexType>

    <!--The end of authors definition-->



    <simpleType name="CardYear">
        <restriction base="gYear">
            <minInclusive value="1880"/>
            <maxInclusive value="2017"/>
        </restriction>
    </simpleType>

    <simpleType name="Theme">
        <restriction base="string">
            <enumeration value="City"/>
            <enumeration value="Nature"/>
            <enumeration value="People"/>
            <enumeration value="Religion"/>
            <enumeration value="Sport"/>
            <enumeration value="Architecture"/>
        </restriction>
    </simpleType>

    <simpleType name="Valuable">
        <restriction base="string">
            <enumeration value="Historical"/>
            <enumeration value="Collectible"/>
            <enumeration value="Thematic"/>
        </restriction>
    </simpleType>

    <simpleType name="Type">
        <restriction base="string">
            <enumeration value="Congratulatory"/>
            <enumeration value="Promotional"/>
            <enumeration value="Ordinary"/>
        </restriction>
    </simpleType>

</schema>

=== matusievic/JWD_Task03_3/src/main/resources/xml/oldcards.xml
<?xml version="1.0" encoding="UTF-8" ?>
<tc:oldcards xmlns:tc="http://www.tc.by/oldcards"
          xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
          xsi:schemaLocation="http://www.tc.by/oldcards oldcards.xsd">

    <card id="ID-0">
        <country>Belarus</country>
        <year>1993</year>
        <authors isKnown="true">
            <author>
                <name>Mikita</name>
                <surname>Jurevic</surname>
            </author>
        </authors>
        <theme>Architecture</theme>
        <valuable>Collectible</valuable>
        <type>Ordinary</type>
    </card>
    <card id="ID-1">
        <country>Lithuania</country>
        <year>2003</year>
        <theme>Architecture</theme>
        <valuable>Thematic</valuable>
        <type>Congratulatory</type>
    </card>
    <card id="ID-2">
        <country>Finland</country>
        <year>1998</year>
        <authors isKnown="true">
            <author>
                <name>John</name>
                <surname>Makarainen</surname>
            </author>
        </authors>
        <theme>City</theme>
        <valuable>Thematic</valuable>
        <type>Promotional</type>
    </card>
    <card id="ID-3">
        <country>Belarus</country>
        <year>2008</year>
        <authors isKnown="true">
            <author>
                <name>Dzmitryj</name>
                <surname>Kuzmienka</surname>
            </author>
        </authors>
        <theme>Sport</theme>
        <valuable>Thematic</valuable>
        <type>Promotional</type>
    </card>
    <card id="ID-4">
        <country>UK</country>
        <year>2003</year>
        <authors isKnown="true">
            <author>
                <name>Mike</name>
                <surname>Shakespeare</surname>
            </author>
        </authors>
        <theme>Architecture</theme>
        <valuable>Collectible</valuable>
        <type>Congratulatory</type>
    </card>

    <card id="ID-5">
        <country>Poland</country>
        <year>2012</year>
        <authors isKnown="true">
            <author>
                <name>Kasia</name>
                <surname>Wozniak</surname>
            </author>
        </authors>
        <theme>Nature</theme>
        <valuable>Collectible</valuable>
        <type>Ordinary</type>
    </card>
    <card id="ID-6">
        <country>USA</country>
        <year>1992</year>
        <authors isKnown="true">
            <author>
                <name>John</name>
                <surname>Doe</surname>
            </author>
        </authors>
        <theme>Religion</theme>
        <valuable>Collectible</valuable>
        <type>Ordinary</type>
    </card>
    <card id="ID-7">
        <country>BSSR</country>
        <year>1932</year>
        <authors isKnown="true">
            <author>
                <name>Vasil</name>
                <surname>Mickievic</surname>
            </author>
        </authors>
        <theme>City</theme>
        <valuable>Historical</valuable>
        <type>Ordinary</type>
    </card>
    <card id="ID-8">
        <country>Latvia</country>
        <year>2001</year>
        <authors isKnown="true">
            <author>
                <name>Andris</name>
                <surname>Shnarskis</surname>
            </author>
        </authors>
        <theme>City</theme>
        <valuable>Collectible</valuable>
        <type>Congratulatory</type>
    </card>
    <card id="ID-9">
        <country>Norway</country>
        <year>1901</year>
        <authors isKnown="true">
            <author>
                <name>Eric</name>
                <surname>Bjorndalen</surname>
            </author>
        </authors>
        <theme>Nature</theme>
        <valuable>Historical</valuable>
        <type>Ordinary</type>
    </card>
    <card id="ID-10">
        <country>Belarus</country>
        <year>1992</year>
        <authors isKnown="true">
            <author>
                <name>Valiancin</name>
                <surname>Zakreuski</surname>
            </author>
        </authors>
        <theme>Religion</theme>
        <valuable>Collectible</valuable>
        <type>Ordinary</type>
    </card>
    <card id="ID-11">
        <country>BSSR</country>
        <year>1927</year>
        <authors isKnown="true">
            <author>
                <name>Jakub</name>
                <surname>Kolas</surname>
            </author>
        </authors>
        <theme>Architecture</theme>
        <valuable>Historical</valuable>
        <type>Ordinary</type>
    </card>
    <card id="ID-12">
        <country>Estonia</country>
        <year>2000</year>
        <authors isKnown="true">
            <author>
                <name>Lena</name>
                <surname>Harma</surname>
            </author>
        </authors>
        <theme>Architecture</theme>
        <valuable>Collectible</valuable>
        <type>Promotional</type>
    </card>
    <card id="ID-13">
        <country>BSSR</country>
        <year>1955</year>
        <authors isKnown="true">
            <author>
                <name>Kastus</name>
                <surname>Davydzionak</surname>
            </author>
        </authors>
        <theme>Nature</theme>
        <valuable>Historical</valuable>
        <type>Ordinary</type>
    </card>
    <card id="ID-14" isSent="false">
        <country>Germany</country>
        <year>2009</year>
        <authors isKnown="true">
            <author>
                <name>Magdalena</name>
                <surname>Noiner</surname>
            </author>
        </authors>
        <theme>Nature</theme>
        <valuable>Thematic</valuable>
        <type>Promotional</type>
    </card>
    <card id="ID-15" isSent="true">
        <country>Belarus</country>
        <year>2012</year>
        <authors isKnown="true">
            <author>
                <name>Anastasia</name>
                <surname>Dubarezava</surname>
            </author>
        </authors>
        <theme>Architecture</theme>
        <valuable>Thematic</valuable>
        <type>Ordinary</type>
    </card>
</tc:oldcards>
